CREATE DATABASE QLBH_FastFood
GO

USE QLBH_FastFood
GO

CREATE TABLE CHUCVU
(
	MaCV INT,
	TenCV NVARCHAR(20),
	HS_Luong FLOAT,
	CONSTRAINT PK_CV PRIMARY KEY(MaCV)
)
GO

CREATE TABLE NHANVIEN
(
	MaNV INT,
	HoTen NVARCHAR(30),
	GT BIT,
	CMND VARCHAR(15),
	SDT VARCHAR(12),
	DiaChi NVARCHAR(50),
	TT_Lam BIT,
	MatKhau VARCHAR(50),
	MaCV INT,
	CONSTRAINT PK_NV PRIMARY KEY(MaNV),
	CONSTRAINT FK_NV_CV FOREIGN KEY(MaCV) REFERENCES dbo.CHUCVU(MaCV)
)
GO

CREATE TABLE CA
(
	MaCa DATETIME,--Thanh DateTime
	SoGio INT DEFAULT(5),
	CONSTRAINT PK_CA PRIMARY KEY(MaCa)
)
GO

CREATE TABLE DIEMDANH
(
	MaNV INT,
	MaCa DATETIME,--Chuyen Thanh DateTime
	CONSTRAINT PK_DD PRIMARY KEY(MaCa,MaNV),
	CONSTRAINT FK_DD_NV FOREIGN KEY(MaNV) REFERENCES dbo.NHANVIEN(MaNV),
	CONSTRAINT FK_DD_CA FOREIGN KEY(MaCa) REFERENCES dbo.CA(MaCa)
)
GO

CREATE TABLE LUONG
(
	MaNV INT,
	Thang INT,
	Nam INT,
	NgayTL DATE,
	LuongCB INT,
	LuongTong INT DEFAULT(0),
	CONSTRAINT PK_L PRIMARY KEY(MaNV,Thang,Nam)
)
GO


CREATE TABLE NGUYENLIEU
(
	MaNL INT,
	TenNL NVARCHAR(30),
	GiaNL INT NOT NULL,
	DonVi NVARCHAR(15),
	SLTonKho INT NOT NULL,
	TT_Ban BIT,
	CONSTRAINT PK_NL PRIMARY KEY(MaNL)
)
GO

CREATE TABLE SANPHAM --them transaction
(
	MaSP INT,
	HinhSP IMAGE,
	TenSP NVARCHAR(30),
	TT_Ban BIT,
	TT_Con BIT,--moi them
	LoiNhuan FLOAT NOT NULL,
	GiamGia FLOAT NOT NULL,
	CONSTRAINT PK_SP PRIMARY KEY(MaSP)
)
GO



CREATE TABLE CHEBIEN
(
	MaSP INT,
	MaNL INT,
	SoLuong INT NOT NULL,
	CONSTRAINT PK_CB PRIMARY KEY(MaSP,MaNL),
	CONSTRAINT FK_CB_SP FOREIGN KEY (MaSP) REFERENCES dbo.SANPHAM(MaSP),
	CONSTRAINT FK_CB_NL FOREIGN KEY (MaNL) REFERENCES dbo.NGUYENLIEU(MaNL)
)
GO

CREATE TABLE HOADON
(
	MaHD INT,
	TongTien INT NOT NULL DEFAULT(0),
	TongGiaSP INT NOT NULL DEFAULT(0),
	Ngay DATE,
	TT_HD BIT,
	CONSTRAINT PK_HD PRIMARY KEY(MaHD)
)
GO

CREATE TABLE CHITIET_HD
(
	MaHD INT,
	MaSP INT,
	SL INT NOT NULL,
	CONSTRAINT PK_CT PRIMARY KEY(MaHD,MaSP),
	CONSTRAINT FK_CT_HD FOREIGN KEY (MaHD) REFERENCES dbo.HOADON(MaHD),
	CONSTRAINT FK_CT_SP FOREIGN KEY (MaSP) REFERENCES dbo.SANPHAM(MaSP)
)
GO

CREATE TABLE THONGKE_T
(
	Thang INT,
	Nam INT,
	TongLuong INT NOT NULL DEFAULT(0),
	TongGiaNL INT NOT NULL DEFAULT(0),
	TongDoanhThu INT NOT NULL DEFAULT(0),
	CONSTRAINT PK_TK PRIMARY KEY(Thang,Nam)
)
GO

